version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: expiry_postgres

    environment:
      POSTGRES_DB: expiry_db
      POSTGRES_USER: expiry_user
      POSTGRES_PASSWORD: expiry_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expiry_user -d expiry_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4

    container_name: expiry_pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: