"""
community/services/community_alert_service.py
Pure business logic for PGN Community Safety Alert Engine (CSAE).
Evaluates, generates, updates, and tracks safety alerts on top of issue clusters.
"""
import uuid
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.community.models.issue_cluster import IssueCluster
from app.community.models.cluster_intelligence import ClusterIntelligence
from app.community.models.safety_alert import SafetyAlert, AlertHistory, AlertNotification


def _generate_alert_code(db: Session) -> str:
    """Generate sequential unique code like CSA-2026-000001."""
    year = datetime.now(timezone.utc).year
    prefix = f"CSA-{year}-"
    
    count = db.query(func.count(SafetyAlert.id)).filter(
        SafetyAlert.alert_code.like(f"{prefix}%")
    ).scalar() or 0
    
    seq = count + 1
    while True:
        code = f"{prefix}{seq:06d}"
        exists = db.query(SafetyAlert.id).filter(SafetyAlert.alert_code == code).first() is not None
        if not exists:
            return code
        seq += 1


def calculate_alert_level(risk_score: int) -> str:
    """
    Map risk score to alert level:
    - Risk < 25: INFORMATION
    - Risk 25-49: WATCH
    - Risk 50-74: WARNING
    - Risk 75-89: HIGH_RISK
    - Risk 90+: CRITICAL
    """
    if risk_score < 25:
        return "INFORMATION"
    elif risk_score < 50:
        return "WATCH"
    elif risk_score < 75:
        return "WARNING"
    elif risk_score < 90:
        return "HIGH_RISK"
    return "CRITICAL"


def generate_recommendation(alert_level: str) -> str:
    """Map alert level to recommended actions."""
    if alert_level == "WATCH":
        return "Continue monitoring cluster activity closely. Log any incoming consumer reports."
    elif alert_level == "WARNING":
        return "Increase observation. Prepare communication templates for community warning."
    elif alert_level == "HIGH_RISK":
        return "Start investigation. Notify QA teams and check batch storage conditions."
    elif alert_level == "CRITICAL":
        return "Recommend immediate recall investigation. Issue public safety warnings."
    else:  # INFORMATION
        return "Continue general monitoring. No action required."


def generate_alert(db: Session, cluster_id: uuid.UUID) -> SafetyAlert:
    """Construct and record a new Safety Alert for a cluster."""
    cluster = db.query(IssueCluster).filter(IssueCluster.id == cluster_id).first()
    intel = db.query(ClusterIntelligence).filter(ClusterIntelligence.cluster_id == cluster_id).first()
    
    if not cluster or not intel:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Cluster or cluster intelligence not found.")

    level = calculate_alert_level(intel.risk_score)
    rec_action = generate_recommendation(level)
    code = _generate_alert_code(db)

    # Compile reasons
    reasons = []
    if intel.risk_score >= 80:
        reasons.append(f"Risk Score {intel.risk_score} >= 80")
    if cluster.severity == "CRITICAL":
        reasons.append("Cluster Severity is CRITICAL")
    if cluster.affected_reports_count > 20:
        reasons.append(f"Reports count {cluster.affected_reports_count} > 20")
    if cluster.affected_cities_count > 5:
        reasons.append(f"Cities count {cluster.affected_cities_count} > 5")
    if intel.trend == "RAPIDLY_GROWING":
        reasons.append("Trend is RAPIDLY_GROWING")
    if intel.average_credibility > 80.0:
        reasons.append(f"Average Credibility {intel.average_credibility} > 80")
    if intel.escalation_level in ("URGENT", "CRITICAL"):
        reasons.append(f"Escalation level is {intel.escalation_level}")

    reason_str = ", ".join(reasons) or "Triggered by engine threshold rules."

    alert = SafetyAlert(
        alert_code=code,
        cluster_id=cluster_id,
        alert_level=level,
        status="ACTIVE",
        title=f"Safety Alert: {cluster.primary_issue_type} detected on {cluster.barcode}",
        description=f"Automated alert for cluster {cluster.cluster_code}. Barcode: {cluster.barcode}, Batch: {cluster.batch_number}.",
        recommended_action=rec_action,
        generated_reason=reason_str,
        generated_by="SYSTEM",
        risk_score=intel.risk_score,
        affected_reports=cluster.affected_reports_count,
        affected_users=cluster.affected_users_count,
        affected_cities=cluster.affected_cities_count,
    )
    
    db.add(alert)
    db.commit()
    db.refresh(alert)

    # History Entry
    history = AlertHistory(
        alert_id=alert.id,
        old_status=None,
        new_status="ACTIVE",
        remarks="Alert automatically generated by system rules.",
        changed_by="SYSTEM",
    )
    db.add(history)

    # Notification Log
    notification = AlertNotification(
        alert_id=alert.id,
        notification_type="SYSTEM",
        recipient="admin@productguardian.net",
        delivery_status="SENT",
    )
    db.add(notification)

    db.commit()
    db.refresh(alert)
    return alert


def update_alert(
    db: Session, alert: SafetyAlert, cluster: IssueCluster, intel: ClusterIntelligence
) -> SafetyAlert:
    """Refresh alert metrics and levels when cluster parameters change."""
    level = calculate_alert_level(intel.risk_score)
    
    alert.risk_score = intel.risk_score
    alert.affected_reports = cluster.affected_reports_count
    alert.affected_users = cluster.affected_users_count
    alert.affected_cities = cluster.affected_cities_count
    alert.alert_level = level
    alert.recommended_action = generate_recommendation(level)

    db.commit()
    db.refresh(alert)
    return alert


def resolve_alert(db: Session, alert_id: uuid.UUID, remarks: Optional[str] = None) -> SafetyAlert:
    """Transition alert state to RESOLVED."""
    alert = db.query(SafetyAlert).filter(SafetyAlert.id == alert_id).first()
    if not alert:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found.")

    if alert.status == "RESOLVED":
        return alert

    old_status = alert.status
    alert.status = "RESOLVED"
    alert.resolved_at = datetime.now(timezone.utc)

    history = AlertHistory(
        alert_id=alert.id,
        old_status=old_status,
        new_status="RESOLVED",
        remarks=remarks or "Alert marked as RESOLVED.",
        changed_by="SYSTEM",
    )
    db.add(history)
    db.commit()
    db.refresh(alert)
    return alert


def close_alert(db: Session, alert_id: uuid.UUID, remarks: Optional[str] = None) -> SafetyAlert:
    """Transition alert state to CLOSED."""
    alert = db.query(SafetyAlert).filter(SafetyAlert.id == alert_id).first()
    if not alert:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found.")

    if alert.status == "CLOSED":
        return alert

    old_status = alert.status
    alert.status = "CLOSED"

    history = AlertHistory(
        alert_id=alert.id,
        old_status=old_status,
        new_status="CLOSED",
        remarks=remarks or "Alert marked as CLOSED.",
        changed_by="SYSTEM",
    )
    db.add(history)
    db.commit()
    db.refresh(alert)
    return alert


def reopen_alert(db: Session, alert_id: uuid.UUID, remarks: Optional[str] = None) -> SafetyAlert:
    """Re-open a resolved or closed alert back to ACTIVE."""
    alert = db.query(SafetyAlert).filter(SafetyAlert.id == alert_id).first()
    if not alert:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found.")

    if alert.status == "ACTIVE":
        return alert

    old_status = alert.status
    alert.status = "ACTIVE"
    alert.resolved_at = None

    history = AlertHistory(
        alert_id=alert.id,
        old_status=old_status,
        new_status="ACTIVE",
        remarks=remarks or "Alert re-opened automatically as cluster became active again.",
        changed_by="SYSTEM",
    )
    db.add(history)
    db.commit()
    db.refresh(alert)
    return alert


def evaluate_cluster(db: Session, cluster_id: uuid.UUID) -> Optional[SafetyAlert]:
    """
    Check if a cluster satisfies any threshold criteria for alerts.
    Generates new alerts, updates existing active ones, re-opens resolved ones,
    or auto-resolves alerts if the cluster itself gets resolved.
    """
    cluster = db.query(IssueCluster).filter(IssueCluster.id == cluster_id).first()
    intel = db.query(ClusterIntelligence).filter(ClusterIntelligence.cluster_id == cluster_id).first()
    
    if not cluster or not intel:
        return None

    # Check alert rules criteria
    met = (
        intel.risk_score >= 80
        or cluster.severity == "CRITICAL"
        or cluster.affected_reports_count > 20
        or cluster.affected_cities_count > 5
        or intel.trend == "RAPIDLY_GROWING"
        or intel.average_credibility > 80.0
        or intel.escalation_level in ("URGENT", "CRITICAL")
    )

    existing = db.query(SafetyAlert).filter(SafetyAlert.cluster_id == cluster_id).first()

    if met:
        # Re-open or update
        if existing:
            if existing.status in ("RESOLVED", "CLOSED") and cluster.status != "RESOLVED":
                reopen_alert(db, existing.id)
            return update_alert(db, existing, cluster, intel)
        else:
            return generate_alert(db, cluster_id)
    else:
        # Check auto-resolution
        if existing and existing.status in ("ACTIVE", "ACKNOWLEDGED", "UNDER_INVESTIGATION"):
            if cluster.status == "RESOLVED":
                return resolve_alert(db, existing.id, "Cluster status updated to RESOLVED.")
            # Otherwise we update the alert metrics even if it's below criteria threshold
            return update_alert(db, existing, cluster, intel)

    return existing


def recalculate_all_alerts(db: Session) -> int:
    """Force re-evaluation of threshold rules across all clusters."""
    clusters = db.query(IssueCluster.id).all()
    count = 0
    for c in clusters:
        evaluate_cluster(db, c.id)
        count += 1
    return count


def get_alert(db: Session, alert_id: uuid.UUID) -> SafetyAlert:
    """Retrieve single alert. Raises 404 if not found."""
    from fastapi import HTTPException
    alert = db.query(SafetyAlert).filter(SafetyAlert.id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=404,
            detail={
                "error": "ALERT_NOT_FOUND",
                "message": f"Safety alert '{alert_id}' not found.",
            },
        )
    return alert


def list_alerts(
    db: Session,
    alert_level: Optional[str] = None,
    status: Optional[str] = None,
    risk_score: Optional[int] = None,
    cluster_id: Optional[uuid.UUID] = None,
    severity: Optional[str] = None,
    date_from: Optional[datetime] = None,
    date_to: Optional[datetime] = None,
    skip: int = 0,
    limit: int = 20,
) -> List[SafetyAlert]:
    """Search and filter safety alerts."""
    query = db.query(SafetyAlert)

    if alert_level:
        query = query.filter(SafetyAlert.alert_level == alert_level)
    if status:
        query = query.filter(SafetyAlert.status == status)
    if risk_score is not None:
        query = query.filter(SafetyAlert.risk_score >= risk_score)
    if cluster_id:
        query = query.filter(SafetyAlert.cluster_id == cluster_id)
        
    if severity:
        query = query.join(IssueCluster).filter(IssueCluster.severity == severity)
        
    if date_from:
        query = query.filter(SafetyAlert.created_at >= date_from)
    if date_to:
        query = query.filter(SafetyAlert.created_at <= date_to)

    return query.order_by(SafetyAlert.risk_score.desc()).offset(skip).limit(limit).all()


def get_dashboard_statistics(db: Session) -> Dict[str, Any]:
    """Compile safety alerts dashboard statistics."""
    total = db.query(func.count(SafetyAlert.id)).scalar() or 0
    active = db.query(func.count(SafetyAlert.id)).filter(SafetyAlert.status == "ACTIVE").scalar() or 0
    resolved = db.query(func.count(SafetyAlert.id)).filter(SafetyAlert.status == "RESOLVED").scalar() or 0
    critical = db.query(func.count(SafetyAlert.id)).filter(SafetyAlert.alert_level == "CRITICAL").scalar() or 0

    newest = db.query(SafetyAlert).order_by(SafetyAlert.created_at.desc()).first()
    highest_risk = db.query(SafetyAlert).order_by(SafetyAlert.risk_score.desc()).first()

    # Resolution Time Average (in hours)
    resolved_alerts = db.query(SafetyAlert.created_at, SafetyAlert.resolved_at).filter(
        SafetyAlert.resolved_at.isnot(None)
    ).all()

    avg_res_hours = 0.0
    if resolved_alerts:
        diffs = [(r - c).total_seconds() / 3600.0 for c, r in resolved_alerts]
        avg_res_hours = round(sum(diffs) / len(diffs), 2)

    return {
        "total_alerts": total,
        "active_alerts": active,
        "critical_alerts": critical,
        "resolved_alerts": resolved,
        "newest_alert": newest,
        "highest_risk_alert": highest_risk,
        "average_resolution_time": avg_res_hours,
    }
